name: Reusable Deploy
on:
  workflow_call:
    inputs:
      artifact-name:
        description: The name of deployable files
        required: false
        default: dist
        type: string
    outputs:
      result:
        description: Result of the deploy
        value: ${{ jobs.deploy.outputs.outcome }}
#   secrets:
#     some-secret:
#         required:
#         type:

jobs:
  deploy:
    outputs:
      outcome: ${{ steps.set-result.outputs.step-result }}
    runs-on: ubuntu-latest
    steps:
      - name: Get code
        uses: actions/download-artifact@v4
        with:
          name: ${{ inputs.artifact-name }}
      - name: List files
        run: ls
      - name: Output info
        run: echo 'Deploying & uploading...'
      - name: Set result output
        id: set-result
        run: echo 'step-result=success' >> $GITHUB_OUTPUT
